version: '0.0.1.{build}'

environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
  PATH: "%PYTHON%;%PYTHON%\\scripts;C:\\MinGW\\bin;%PATH%"

install:
  # We need wheel installed to build wheels
  - pip install wheel
  - python setup.py sdist bdist_wheel
  - pip install .[ci]

build: off

# RDP
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

test_script:
  - pytest -sv --cov=arggen --cov=tests tests/
  - codecov

artifacts:
  - path: 'dist\*'
