version: '0.0.1.{build}'

environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
  PATH: "%PYTHON%;%PYTHON%\\scripts;%PATH%"
  CXX: "C:\\MinGW\\bin\\g++.exe"

install:
  # We need wheel installed to build wheels
  - pip install wheel
  - python setup.py sdist bdist_wheel
  - pip install .[ci]
  # debug
  - C:\MinGW\bin\g++.exe -Wall -Wextra -std=c++11 -c tests/catch.cpp

build: off

test_script:
  - pytest -sv --cov=arggen --cov=tests tests/
  - codecov

artifacts:
  - path: 'dist\*'
