version: '0.0.1.{build}'

environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
  PATH: "%PYTHON%;%PYTHON%\\scripts;%PATH%"

install:
  # We need wheel installed to build wheels
  - pip install wheel
  - python setup.py sdist bdist_wheel
  - pip install .[ci]

build: off

test_script:
  - pytest -sv --cov=arggen --cov=tests tests/
  - codecov

artifacts:
  - path: 'dist\*'
